------------------------------------------------------------------------

title: "Shiny Dash"

```{r}
#install packages
install.packages("shiny")
install.packages("shinydashboard")
install.packages("plotly")
install.packages("ggplot2")
BiocManager::install("EBSeq")

```

```{r}
#load packages
library(shiny)
library(shinydashboard)
library(plotly)
library(ggplot2)
library(EBSeq)
```

```{r}
#load relevant data

breast_PCA_data <- read.csv("breast_PCA_data.csv")
breast_PCA_data <- as.data.frame(breast_PCA_data)
breast_normalized_matrix_data <- read.csv("breast_normalized_matrix.csv")
breast_normalized_matrix_data <- as.data.frame(breast_normalized_matrix_data)
breast_table <- read.csv("breast_table.csv")
breast_table <- as.table(breast_table)


```

```{r}
#define ui
ui <- dashboardPage(
  dashboardHeader(title = "Cancer Dependency Map Portal"),
  dashboardSidebar(
    selectInput("cancer_type", "Select a cancer type", c("Breast", "Lung", "Myeloma"))
  ),
  dashboardBody(
    fluidRow(
      column(width = 4, plotlyOutput("plot1")),
      column(width = 4, plotOutput("plot2")),
      #column(width = 6, plotOutput("plot3")),
      column(width = 4, plotOutput("table1"))
    )
  )
)
```

```{r}
#define the server

#loading the PCA plot -- plotly
server <- function(input, output) {
  
  output$plot1 <- renderPlotly({
    if (input$cancer_type == "Breast") {
       plot_ly(data = breast_PCA_data, x = ~PC1, y = ~PC2, color= ~sex, width = 500, height = 500, text = ~paste("Cell line: ", DepMap_ID, '$<br>Primary Disease:', primary_disease))
    }
   # } else if (input$cancer_type == "Lung") {
      #plot_ly(data = lung_PCA_data, x = ~PC1, y = ~PC2, color= ~sex, width = 500, height = 500, text = ~paste("Cell line: ", DepMap_ID, '$<br>Primary Disease:', primary_disease))
   # }
    #} else if (input$cancer_type == "Myeloma") {
    #  plot_ly(data = myeloma_PCA_data, x = ~PC1, y = ~PC2, color= ~sex, width = 500, height = 500, text = ~paste("Cell line: ", DepMap_ID, '$<br>Primary Disease:', primary_disease))
    #}
  })
  
  #loading the heatmaps -- ggplot
  output$plot2 <- renderPlot({
    if (input$cancer_type == "Breast") {
      heatmap.2(breast_normalized_matrix, scale="row", trace="none", Colv=F) }
   #  else if (input$cancer_type == "Lung") {
    #  heatmap.2(lung_normalized_matrix, scale="row", trace="none", Colv=F) }
    #} else if (input$cancer_type == "Myeloma") {
     # heatmap.2(myeloma_normalized_matrix, scale="row", trace="none", Colv=F) }
    #}
  })
  #loading the boxplots -- plotly
#  output$plot3 <- renderPlotly({
  #  if (input$cancer_type == "Breast") {
      #ggplot }
   #  else if (input$cancer_type == "Lung") {
    #  ggplot
    #} else if (input$cancer_type == "Myeloma") {
     # ggplot
    #}
#  })
  
  #load the table with genes and FC score
  output$table1 <- renderTable({
    if (input$cancer_type == "Breast") {
       as.table(breast_table)}
   #  else if (input$cancer_type == "Lung") {
    #  table(lung_table)
    #} else if (input$cancer_type == "Myeloma") {
     # table(myeloma_table)
    #}
  })
}

```

```{r}
#run app
shinyApp(ui = ui, server = server)
```
